kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lemur
subjects:
  - kind: ServiceAccount
    name: lemur
    namespace: lemur
roleRef:
  kind: ClusterRole
  name: secret-applier
  apiGroup: rbac.authorization.k8s.io
