apiVersion: v1
kind: Service
metadata:
  namespace: lemur
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
